Name = "Rain Yun/雨云"
Description = ''''''
URL = "https://www.rainyun.com"
Code = "rainyun"
Since = "v4.21.0"

Example = '''
RAINYUN_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --email you@example.com --dns rainyun -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    RAINYUN_API_KEY = "API key"
  [Configuration.Additional]
    RAINYUN_POLLING_INTERVAL = "Time between DNS propagation check"
    RAINYUN_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    RAINYUN_TTL = "The TTL of the TXT record used for the DNS challenge"
    RAINYUN_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.apifox.cn/apidoc/shared-a4595cc8-44c5-4678-a2a3-eed7738dab03/api-151416609"
